%%
%% @doc Records generated by feed parser
%%


%%
%% @doc News channel information
%%
-record(newsChannel, {
    id,                 % Channel id
    title="",           % Channel title
    link,               % The URL to the website corresponding to the channel
    description="",     % Channel description
    language,           % Channel language
    categories=[],      % Channel categories
    icon,               % Channel icon
    logo,               % Channel logo
    published,          % Publication date and time
    updated,            % The last time the content of the channel changed
    copyright,          % Channel copyrights
    generator="",       % User agent used to generate news channel content
    authors=[],         % Authors of the news channel
    contributors=[],    % Contributors to the news channel
    webmaster           % Person responsible for technical issues
    }).
